version: '3.8'

services:
  bot:
    image: masoudse7en/bargheman:latest
    container_name: bargheman_bot
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Tehran
    networks:
      - bot_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  bot_network:
    driver: bridge